[강현구] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/28-westagram-backend-4-team pull request #14
Opened 2021-12-22 08:42 UTC by nine57

## 수정 사항 간략한 한줄 요약
- 비밀번호 암호화 설정
		 
## 수정 사항들 자세한 내용
- bcrypt를 사용한 비밀번호 암호화

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-22 09:14 UTC, kyeongraekim requested changes
아래 내용 확인하고 수정 고민해보세요!~

2021-12-22 09:14 UTC, kyeongraekim commented on students/hyeongu/users/views.py
> +            hashed_password = User.objects.get(email=email).password.encode('utf-8')
get() 메소드에서 원하는 객체를 발견하지 못한다면 Model.DoesNotExist 에러가 날 것 입니다. 해당 내용도 아래 except문에서 같이 처리해주세요!~

2021-12-22 09:23 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정 반영해보세요!~

2021-12-22 11:30 UTC, nine57 commented on students/hyeongu/users/views.py
> +            hashed_password = User.objects.get(email=email).password.encode('utf-8')
수정 완료 했습니다!
계정 정보(email,password)와 관련된 정보에서 오류 발생 시, 오류 발생 정보를 특정짓지 않고 전부 'INVALID_USER'로 오류 문구를 통일시켰습니다. (보안 이슈)

2021-12-23 02:36 UTC, Kang-kyunghun commented
LGTM

2021-12-23 02:36 UTC, merged