ADD: make database modeling (mission 2)
wecode-bootcamp-korea/28-westagram-backend-4-team pull request #5
Opened 2021-12-17 02:30 UTC by kimjy10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 앱 생성 및 DB 생성
- 		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users라는 이름의 앱을 만들고, models.py에 DB관련 정보 기입하였습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-17 02:41 UTC, kyeongraekim requested changes
아래 내용 확인하시고 수정 반영해주세요!~

2021-12-17 02:41 UTC, kyeongraekim commented on students/kimjy/westagram/users/models.py
> +# Create your models here.
불필요한 주석은 삭제해주세요!~

2021-12-17 02:41 UTC, kyeongraekim commented on students/kimjy/westagram/users/models.py
> +class Users(models.Model):
파이썬 컨벤션상 Class명 네이밍은 꼭 단수로 해주셔야합니다!~ 아래 모델명은 복수로 알맞게 잘 작성해주셨네요! 둘 차이를 항상 유의해주세요~

2021-12-17 02:41 UTC, kyeongraekim commented on students/kimjy/westagram/users/models.py
> +    user_name     = models.CharField(max_length=45)
username이라는 용어가 영문으로 통상적으로 쓰이기 때문에 언더바는 굳이 필요 없어 보입니다

2021-12-17 02:41 UTC, kyeongraekim commented on students/kimjy/westagram/users/models.py
> +    password      = models.CharField(max_length=50)
비밀번호는 추후 암호화 가능성을 고려하여 보다 더 긴 해싱된 문자열이 들어올 예정임으로 max_length를 최소 256자로는 맞추어 주세요!~

2021-12-17 02:41 UTC, kyeongraekim commented on students/kimjy/westagram/users/models.py
> +    profile_desc  = models.CharField(max_length=500, blank=True)
개발자에게 있어서 변수명 네이밍은 매우 중요합니다. 제 3자가 봐도 무슨 내용인지 알 수 있게 가독성 향상을 위해서 원어 전체를 풀어서 써주세요!~

2021-12-17 03:07 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +# Create your models here.
주석 삭제하였습니다.

2021-12-17 03:07 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +class Users(models.Model):
class 명을 단수로 변경하였습니다.

2021-12-17 03:07 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +    user_name     = models.CharField(max_length=45)
언더바 삭제하였습니다.

2021-12-17 03:07 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +    password      = models.CharField(max_length=50)
문자열을 256으로 설정하였습니다.

2021-12-17 03:08 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +    profile_desc  = models.CharField(max_length=500, blank=True)
변수 명 변경하였습니다.

2021-12-17 03:26 UTC, kyeongraekim requested changes
아래 내용 확인해주시고 반영 고려해보세요!~

2021-12-17 03:26 UTC, kyeongraekim commented on students/kimjy/westagram/users/models.py
> +    email_address = models.CharField(max_length=300, null=True)
email을 기준으로 로그인을 기획해 보는 것은 어떨까요? 이메일의 중복을 피할 수 있게 unique=True를 설정해주시고, 꼭 데이터가 입력 될 수 있게 null=True는 지우는 기획을 한 번 고려해보세요!~

2021-12-17 04:26 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +    email_address = models.CharField(max_length=300, null=True)
네 수정완료하였습니다.

2021-12-17 07:20 UTC, Kang-kyunghun requested changes

2021-12-17 07:20 UTC, Kang-kyunghun commented on students/kimjy/westagram/users/models.py
> +    profile_bio   = models.CharField(max_length=500, blank=True)
1. brank=True을 사용한 이유를 코멘트로 남겨주세요.
2. image 같은 경우 이미지의 url 주소를 저장하게 되는 url 주소가 생각보다 긴 경우도 있어 1000정도로 여유롭게 잡으며 좋을 것 같아요
3. profile_bio를 무엇을 저장하는 field 인가요?(궁금)
4. 데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-17 07:33 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +    profile_bio   = models.CharField(max_length=500, blank=True)
1. 프로필 이미지와 프로필 바이오는 회원가입 후 입력할 수 있어서 blank를 True로 하였습니다. 또, 이미지와 자기소개를 비워두는 유저도 있을 가능성이 있습니다. 
2. 리뷰 반영하였습니다.
3. 프로필 바이오는 짧은 자기소개를 저장할 수 있는 컬럼입니다. 인스타그램에도 짧은 자기소개를 저장할 수 있는 공간이 있었습니다.
4. 리뷰 반영하였습니다.

2021-12-18 01:58 UTC, Kang-kyunghun requested changes

2021-12-18 01:58 UTC, Kang-kyunghun commented on students/kimjy/westagram/users/models.py
> +    profile_bio   = models.CharField(max_length=500, blank=True)
blank=True는 Django form과 관련된 속성입니다. 따라서 회원 가입 후 입력하는 것이 목적이라면, null 이나 default 속성을 주시면 좋을 것 같습니다.

2021-12-18 02:39 UTC, kimjy10 commented on students/kimjy/westagram/users/models.py
> +    profile_bio   = models.CharField(max_length=500, blank=True)
네, 리뷰반영하였습니다 감사합니다!

2021-12-18 02:45 UTC, Kang-kyunghun commented
LGTM!!

2021-12-18 02:45 UTC, merged