[강현구] Mission 2: 모델링
wecode-bootcamp-korea/28-westagram-backend-4-team pull request #6
Opened 2021-12-17 06:03 UTC by nine57

## 수정 사항 간략한 한줄 요약
- users app 추가, table model 작성
		 
## 수정 사항들 자세한 내용
- users app 추가 (setting 파일에 users app 추가)
- model 파일 : user table field setting

## 기타 질문 및 특이 사항
- password의 글자수 제한을 위해서 min~max로 하한범위도 지정했는데, 이 부분은 프론트에서 받을 때 필터링해서 받는 것인가요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-17 07:15 UTC, Kang-kyunghun requested changes

2021-12-17 07:15 UTC, Kang-kyunghun commented on students/hyeongu/westagram/settings.py
> +    'westagram'
```suggestion
    'django.contrib.staticfiles',
    'corsheaders',
    'westagram'
```
1. 라인 잘 맞춰주세요.
2. 추가하는 app 이름이 westagram이 맞는지 다시 확인해 보세요.

2021-12-17 07:15 UTC, Kang-kyunghun commented on students/hyeongu/users/models.py
> +
1. 회사마다 컨벤션이 다르지만, 위코드 안에서는 되도록 주석을 사용하지 않습니다. 특히 지금 같은 경유 변수명이 무엇을 의미하는 확실히 알 수 있기 때문에 주석은 제거해 주세요.
2. 중복되면 안 되는 값들에 unique=True 속성을 더해주면 좋을 것 같습니다.
3. 데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-17 08:49 UTC, nine57 commented on students/hyeongu/westagram/settings.py
> +    'westagram'
1. 라인 정리 완료했습니다!
2. 오기입 수정 완료했습니다. (westagram -> users)

2021-12-17 08:51 UTC, nine57 commented on students/hyeongu/users/models.py
> +
1. 불필요한 주석들 제거 완료했습니다.
2. email, mobile_number, username에 unique값 설정했습니다.
  각각에 대해 일반적으로 중복발생 없이 고유값을 갖고 있다고 판단했습니다.
3. 두 컬럼 생성 완료했습니다.

2021-12-18 01:54 UTC, Kang-kyunghun requested changes

2021-12-18 01:54 UTC, Kang-kyunghun commented on students/hyeongu/users/models.py
> +    mobile_number = models.CharField(max_length = 50, null = True, unique = True)
null과 unique을 같이 사용하면 위험합니다. null로 유일한 값으로 볼 수 있어서 null을 중복으로 둘 수 없게 됩니다. 
여기서는 unique을 빼는 것이 맞을 것 같습니다.

2021-12-18 06:57 UTC, nine57 commented on students/hyeongu/users/models.py
> +    mobile_number = models.CharField(max_length = 50, null = True, unique = True)
null도 하나의 값으로 인식을 하게되는군요...
unique는 빼고 null만 남겨서 수정했습니다.

2021-12-18 07:00 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-18 07:00 UTC, merged

2021-12-18 07:08 UTC, nine57 commented
THX!