[김재엽] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-4-team pull request #7
Opened 2021-12-20 04:48 UTC by kimjy10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 기능을 구현하였습니다.
		 
## 수정 사항들 자세한 내용

- 이메일로 로그인할 수 있음
- http 통신으로 전달받은 key 중 필요한 key가 모두 있는 지 확인
- 이메일 및 비밀번호가 올바른지 확인
- DB작성 전에 email 중복 여부를 확인
- 실패시 상황에 알맞은 에러 반환
- 성공시 201 코드 반환

## 기타 질문 및 특이 사항
- 어떤 기능 및 변수인지 알아보기 쉽도록 변수명 및 함수명을 길게 지었습니다. 이렇게 길게 지어도 괜찮을까요?
(예를들어, 함수명은 check_chracter_policy, 변수명은 necessary_key_list) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-20 05:19 UTC, kimjy10 commented
2번째 커밋 수정사항:
-전화번호는 optional key인데, 자동으로 참조하여 에러가 발생하는 버그가 있었습니다.
-따라서 JSON에 있는 키들을 중에서 필수적으로 필요한 3개의 key들(username, email, password)의 값만 저장하고, Phone_number의 경우에는 optional 하게 설정하였습니다.
-따라서 일단 3개의 키값으로 DB를 생성하고, 추후에 phone_number가 있으면 user row에서 update하는 방법으로 진행하였습니다.

2번째 커밋 중 질문사항:
- 현재는 backend 부분만 따로 개발하는 상황이라서 httpie로 통신을 하는 것 같습니다. 따라서 이를 사용해서 여러 테스트 케이스를 만들고 싶은데, bash shell script로 작성하는 것이 좋을까요? 아니면 python script로 작성하는 것이 좋을까요?
- 또 bash shell script로 진행한다면(혹은 python script), github에는 업로드 하지 않는 것이 좋겠죠..?

2021-12-20 08:45 UTC, kimjy10 commented
안녕하세요? 피드백주신 내용을 바탕으로 코드를 수정하였습니다.
1. except에서 에러에 맞도록 상세화
2. return을 각 except 구문에 추가
3. 위코드 컨벤션에 맞도록 변경

검토부탁드리겠습니다.

2021-12-21 02:27 UTC, Kang-kyunghun requested changes

2021-12-21 02:27 UTC, Kang-kyunghun commented on students/kimjy/westagram/users/views.py
> +                    user.save()
1. if를 통과하게 되면 error가 raise되기 때문에 else를 굳이 안 사용해도 좋을 것 같습니다.
2. dictionary의 get method을 사용하면 key가 없을 때 default 값을 정할 수 있습니다. 그렇게 된다면 if 구문을 줄일 수 있습니다. 한 번 고민해 보세요.

```suggestion
            if User.objects.filter(email_address=email).exists():
                raise IntegrityError("EMAIL_DUPLICATED_ERROR")

            user = User.objects.create(
                        username      = username,
                        password      = password,
                        email_address = email,
            )
            
            if 'phone_number' in data:
                user.phone_number = data['phone_number']
                user.save()
```

2021-12-21 02:27 UTC, Kang-kyunghun commented on students/kimjy/westagram/users/check_items.py
> +        raise KeyError("["+error_message+"] was not found in http body")
```suggestion
        raise KeyError(f"[{error_message}] was not found in http body")
```
파이썬에서는 이 문법을 더 많이 사용합니다.

2021-12-21 02:27 UTC, Kang-kyunghun commented on students/kimjy/westagram/users/check_items.py
> +def check_dictionary_keys(check_dict:dict, necessary_key_list:list):
들어오는 key 값을 확인하고, 없는 key을 반환 하시려고 하는것 같은데, 지금 같은 경우는 user app 국한 되어 있습니다. 만약에 다른 app 다른 api에서도 모두 적용 할려면 그 수만큼 함수를 만들어야 하는데, 그럼 비효율적이겠죠? 
그래서 이렇게 전체적으로 사용되는 기능같은 경우 class을 만들어서 전체적으로 활요하면 좋을 것 같습니다.
특히 KeyError에 관한 거니 KeyError class 커스텀 하는 것이 적절 할 것 같습니다.

2021-12-21 02:27 UTC, Kang-kyunghun commented on students/kimjy/westagram/users/views.py
> +            check_dictionary_keys(data, login_key_list)
check_dictionary_keys함수와 login_key_list data 모두 같은 모듈에 있는데, view에서 다시 login_key_list을 인자로 넣어서 함수를 실행하는 것이 어색해 보이네요.

2021-12-21 02:27 UTC, Kang-kyunghun commented on students/kimjy/westagram/users/check_items.py
> +
```suggestion
import re

from django.core.exceptions import ValidationError

def validate_email(value) :
    email_regex = re.compile('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
    
    if not email_regex.match(value):
        raise ValidationError('INVALID_EMAIL_ADDRESS')

def validate_password(value) :
    password_regex = re.compile("^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$")
    
    if not password_regex.match(value):
        raise ValidationError('INVALID_PASSWORD')
```
validator.py의 가장 기본 구조 입니다.
비교해 보시고 python 다운 코드가 무엇일지 생각해보면 좋을 것 같아요.

구두로 말씀 드렸듯이 flag을 만들어 조건에 따라 flag을 변화 시키는 것은 C언어 같은 스타일입니다.
flag 없이도 충분히 구현 할 수 있도록 짜는 것이 좀 더 python 다운 코드라고 할 수 있을 것 같습니다.

2021-12-21 05:40 UTC, kimjy10 commented on students/kimjy/westagram/users/views.py
> +                    user.save()
말씀해주신대로 else를 쓰지않았고, dictionary의 value를 가져올 때 get 메소드를 사용하였습니다. 이렇게 사용하니까 코드가 훨씬 간결하게 변한 것 같습니다!

2021-12-21 05:41 UTC, kimjy10 commented on students/kimjy/westagram/users/check_items.py
> +        raise KeyError("["+error_message+"] was not found in http body")
네 코멘트 감사합니다. 말씀해주신대로 수정하였습니다.

2021-12-21 05:42 UTC, kimjy10 commented on students/kimjy/westagram/users/check_items.py
> +def check_dictionary_keys(check_dict:dict, necessary_key_list:list):
코멘트 감사합니다.
말씀해주신대로, westagram안에 checkitem.py를 옮기고 class로 만들었습니다.

2021-12-21 05:43 UTC, kimjy10 commented on students/kimjy/westagram/users/views.py
> +            check_dictionary_keys(data, login_key_list)
코멘트 감사합니다.
말씀해주신대로 키, 데이터 모두 SignUpView 클래스에서 생성하도록 변경하였습니다.

2021-12-21 05:46 UTC, kimjy10 commented on students/kimjy/westagram/users/check_items.py
> +
코멘트 감사합니다.
flag의 경우에는 제가 익숙했던 방법이어서 사용했던 것 같습니다. 파이썬에서는 사용하지 않도록 주의하겠습니다.
말씀해주신 의견 반영하여 수정하였습니다.

2021-12-21 06:56 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-21 06:56 UTC, merged